java_library(
    name = "graphics",
    srcs = glob(["*.java"]),
    deps = [
        "//engine/src/main/java/common/game",
        "@org_lwjgl_lwjgl//jar",
        "@org_lwjgl_lwjgl_opengl//jar",
        "@org_lwjgl_lwjgl_glfw//jar",
    ],
    resources = [
        "//engine/src/main/resources:resources",
    ],
    visibility = ["//visibility:public"],
)
