load("@org_pubref_rules_protobu//go.rules.bzl", "go_proto_library")

go_proto_library(
    name = "go_default_library",
    protos = [
        "messages.proto",
        "mmserver.proto",
    ],
    with_grpc = True,
)
